# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fdfe548aaf3569aa23b393a9b0909220565f3876f07ffeede0293da884ee66aee5e7e976738c2ae34f0ea238b7a5a02bb8866f5946d552ed87e96a276e162e

test:
  secret_key_base: a0d83990cc5a1d8d95706c4a7b059405f5682b8c334c693c4cb605f2a209b328a00345e8eb4a388985f111700e890e3293a966ab38a9b278242d701e3c649a4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
